# Use the official Node.js image as the base image
FROM node:22.13.1

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port your app runs on (e.g., 3000)
EXPOSE 8083

# Define the command to run your app
CMD ["node", "index.js"]
